/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author weslley
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BemVindo = new javax.swing.JLabel();
        SenhaUsuario = new javax.swing.JPasswordField();
        BotaoAcesso = new javax.swing.JButton();
        BotaoPesquisar = new javax.swing.JButton();
        BotaoCadastro = new javax.swing.JButton();
        Cadeado = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        LoginUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        NomePrograma = new javax.swing.JLabel();
        LogoCarrinho = new javax.swing.JLabel();
        TelaProjeto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bemvindo.png"))); // NOI18N
        getContentPane().add(BemVindo);
        BemVindo.setBounds(290, 160, 140, 50);

        SenhaUsuario.setText("sdsdsdsdsdsdsdsd");
        SenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaUsuario);
        SenhaUsuario.setBounds(270, 320, 200, 40);

        BotaoAcesso.setBackground(new java.awt.Color(255, 229, 77));
        BotaoAcesso.setText("Acessar");
        getContentPane().add(BotaoAcesso);
        BotaoAcesso.setBounds(310, 390, 120, 40);

        BotaoPesquisar.setBackground(new java.awt.Color(255, 229, 77));
        BotaoPesquisar.setText("Pesquisar");
        getContentPane().add(BotaoPesquisar);
        BotaoPesquisar.setBounds(570, 410, 120, 40);

        BotaoCadastro.setBackground(new java.awt.Color(255, 229, 77));
        BotaoCadastro.setText("Cadastre-se");
        getContentPane().add(BotaoCadastro);
        BotaoCadastro.setBounds(50, 410, 120, 40);

        Cadeado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadeado.png"))); // NOI18N
        getContentPane().add(Cadeado);
        Cadeado.setBounds(220, 320, 40, 30);

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa1.png"))); // NOI18N
        getContentPane().add(Usuario);
        Usuario.setBounds(220, 240, 40, 80);

        LoginUsuario.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LoginUsuario.setText("Usuário");
        LoginUsuario.setVerifyInputWhenFocusTarget(false);
        LoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(LoginUsuario);
        LoginUsuario.setBounds(270, 260, 200, 40);

        jPanel1.setBackground(new java.awt.Color(255, 229, 77));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 230, 370, 150);

        NomePrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png"))); // NOI18N
        getContentPane().add(NomePrograma);
        NomePrograma.setBounds(250, 120, 300, 50);

        LogoCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5.jpg"))); // NOI18N
        getContentPane().add(LogoCarrinho);
        LogoCarrinho.setBounds(280, 20, 170, 100);

        TelaProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(TelaProjeto);
        TelaProjeto.setBounds(3, 0, 750, 480);

        setSize(new java.awt.Dimension(967, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsuarioActionPerformed

    private void SenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindo;
    private javax.swing.JButton BotaoAcesso;
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JLabel Cadeado;
    private javax.swing.JTextField LoginUsuario;
    private javax.swing.JLabel LogoCarrinho;
    private javax.swing.JLabel NomePrograma;
    private javax.swing.JPasswordField SenhaUsuario;
    private javax.swing.JLabel TelaProjeto;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
