/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author weslley
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Caixa2 = new javax.swing.JTextField();
        TituloEndereco = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        ComplementoEnd = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        CPNJText = new javax.swing.JTextField();
        Caixa1End = new javax.swing.JTextField();
        LoginEmpresa = new javax.swing.JLabel();
        CepEnd = new javax.swing.JLabel();
        BairroEnd = new javax.swing.JLabel();
        EstadoEnd = new javax.swing.JLabel();
        Caixa1 = new javax.swing.JTextField();
        Caixa5End = new javax.swing.JTextField();
        Caixa2End = new javax.swing.JTextField();
        Caixa3End = new javax.swing.JTextField();
        LogadouroEnd = new javax.swing.JLabel();
        Caixa6End = new javax.swing.JTextField();
        NumeroEnd = new javax.swing.JLabel();
        Caixa7End = new javax.swing.JTextField();
        CidadeEnd = new javax.swing.JLabel();
        Caixa8End = new javax.swing.JTextField();
        ContinuarBotao = new javax.swing.JButton();
        CarrinhoIcon = new javax.swing.JLabel();
        TituloEmpresa1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TituloEmpresa = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        SenhaEmpresaRep = new javax.swing.JPasswordField();
        Caixa4 = new javax.swing.JTextField();
        SenhaDados = new javax.swing.JLabel();
        SenhaDados1 = new javax.swing.JLabel();
        SenhaEmpresa = new javax.swing.JPasswordField();
        TelaFundo = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Caixa2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 280, 30));

        TituloEndereco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloEndereco.setText("Endereço");
        getContentPane().add(TituloEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 240, 60));

        Telefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Telefone.setText("Telefone:");
        getContentPane().add(Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 130, 50));

        ComplementoEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComplementoEnd.setText("Complemento:");
        getContentPane().add(ComplementoEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 180, 50));

        CNPJ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CNPJ.setText("CNPJ:");
        getContentPane().add(CNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 50));

        CPNJText.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(CPNJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 350, 30));

        Caixa1End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa1End, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 480, 30));

        LoginEmpresa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LoginEmpresa.setText("Login da Empresa:");
        getContentPane().add(LoginEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, 50));

        CepEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CepEnd.setText("CEP:");
        getContentPane().add(CepEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 130, 50));

        BairroEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BairroEnd.setText("Bairro:");
        getContentPane().add(BairroEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 130, 50));

        EstadoEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EstadoEnd.setText("Estado:");
        getContentPane().add(EstadoEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 130, 50));

        Caixa1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 340, 30));

        Caixa5End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa5End, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 270, 30));

        Caixa2End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa2End, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 260, 30));

        Caixa3End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa3End, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 260, 30));

        LogadouroEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogadouroEnd.setText("Logadouro:");
        getContentPane().add(LogadouroEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 130, 50));

        Caixa6End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa6End, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 390, 30));

        NumeroEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NumeroEnd.setText("Número:");
        getContentPane().add(NumeroEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 130, 50));

        Caixa7End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa7End, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 150, 30));

        CidadeEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CidadeEnd.setText("Cidade:");
        getContentPane().add(CidadeEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 130, 50));

        Caixa8End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa8End, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 220, 30));

        ContinuarBotao.setBackground(new java.awt.Color(255, 229, 77));
        ContinuarBotao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ContinuarBotao.setText("Continuar");
        ContinuarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(ContinuarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 110, 50));

        CarrinhoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho menor.jpg"))); // NOI18N
        getContentPane().add(CarrinhoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 100));

        TituloEmpresa1.setBackground(new java.awt.Color(255, 204, 153));
        TituloEmpresa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloEmpresa1.setText("Dados da Empresa");
        getContentPane().add(TituloEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 240, 60));

        jPanel1.setBackground(new java.awt.Color(255, 229, 77));

        TituloEmpresa.setBackground(new java.awt.Color(255, 204, 153));
        TituloEmpresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloEmpresa.setText("Cadastro do Supermercado");
        jPanel1.add(TituloEmpresa);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 510, 40));

        Nome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Nome.setText("Nome da Empresa:");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 210, 50));

        SenhaEmpresaRep.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(SenhaEmpresaRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 220, 30));

        Caixa4.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 460, 30));

        SenhaDados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SenhaDados.setText("Repita a senha:");
        getContentPane().add(SenhaDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 180, 50));

        SenhaDados1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SenhaDados1.setText("Senha:");
        getContentPane().add(SenhaDados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 50));

        SenhaEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(SenhaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, 30));

        TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        TelaFundo.setText("jLabel1");
        getContentPane().add(TelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 960, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinuarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinuarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BairroEnd;
    private javax.swing.JLabel CNPJ;
    private javax.swing.JTextField CPNJText;
    private javax.swing.JTextField Caixa1;
    private javax.swing.JTextField Caixa1End;
    private javax.swing.JTextField Caixa2;
    private javax.swing.JTextField Caixa2End;
    private javax.swing.JTextField Caixa3End;
    private javax.swing.JTextField Caixa4;
    private javax.swing.JTextField Caixa5End;
    private javax.swing.JTextField Caixa6End;
    private javax.swing.JTextField Caixa7End;
    private javax.swing.JTextField Caixa8End;
    private javax.swing.JLabel CarrinhoIcon;
    private javax.swing.JLabel CepEnd;
    private javax.swing.JLabel CidadeEnd;
    private javax.swing.JLabel ComplementoEnd;
    private javax.swing.JButton ContinuarBotao;
    private javax.swing.JLabel EstadoEnd;
    private javax.swing.JLabel LogadouroEnd;
    private javax.swing.JLabel LoginEmpresa;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel NumeroEnd;
    private javax.swing.JLabel SenhaDados;
    private javax.swing.JLabel SenhaDados1;
    private javax.swing.JPasswordField SenhaEmpresa;
    private javax.swing.JPasswordField SenhaEmpresaRep;
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel TituloEmpresa;
    private javax.swing.JLabel TituloEmpresa1;
    private javax.swing.JLabel TituloEndereco;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
