/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author weslley
 */
public class TelaPesquisaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProduto
     */
    public TelaPesquisaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EncontrarBotao = new javax.swing.JButton();
        Caixa2 = new javax.swing.JTextField();
        MarcaPesquise = new javax.swing.JLabel();
        TituloPesquise = new javax.swing.JLabel();
        CarrinhoIcon = new javax.swing.JLabel();
        NomePesquise = new javax.swing.JLabel();
        Caixa1 = new javax.swing.JTextField();
        PlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        EncontrarBotao.setBackground(new java.awt.Color(255, 229, 77));
        EncontrarBotao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EncontrarBotao.setText("Encontrar");
        getContentPane().add(EncontrarBotao);
        EncontrarBotao.setBounds(410, 350, 110, 50);

        Caixa2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa2);
        Caixa2.setBounds(240, 190, 430, 30);

        MarcaPesquise.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MarcaPesquise.setText("Marca:");
        getContentPane().add(MarcaPesquise);
        MarcaPesquise.setBounds(140, 180, 130, 50);

        TituloPesquise.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TituloPesquise.setText("Pesquise o produto");
        getContentPane().add(TituloPesquise);
        TituloPesquise.setBounds(300, 40, 430, 50);

        CarrinhoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho menor.jpg"))); // NOI18N
        CarrinhoIcon.setText("jLabel1");
        getContentPane().add(CarrinhoIcon);
        CarrinhoIcon.setBounds(120, 20, 100, 80);

        NomePesquise.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NomePesquise.setText("Nome:");
        getContentPane().add(NomePesquise);
        NomePesquise.setBounds(140, 130, 130, 50);

        Caixa1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa1);
        Caixa1.setBounds(230, 140, 460, 30);

        PlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(PlanoDeFundo);
        PlanoDeFundo.setBounds(-4, 0, 1010, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Caixa1;
    private javax.swing.JTextField Caixa2;
    private javax.swing.JLabel CarrinhoIcon;
    private javax.swing.JButton EncontrarBotao;
    private javax.swing.JLabel MarcaPesquise;
    private javax.swing.JLabel NomePesquise;
    private javax.swing.JLabel PlanoDeFundo;
    private javax.swing.JLabel TituloPesquise;
    // End of variables declaration//GEN-END:variables
}
