/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author weslley
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Caixa2 = new javax.swing.JTextField();
        TituloEndereco = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        ComplementoEnd = new javax.swing.JLabel();
        CNPJ = new javax.swing.JLabel();
        Caixa3 = new javax.swing.JTextField();
        Caixa1End = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        CepEnd = new javax.swing.JLabel();
        BairroEnd = new javax.swing.JLabel();
        EstadoEnd = new javax.swing.JLabel();
        Caixa1 = new javax.swing.JTextField();
        Caixa5End = new javax.swing.JTextField();
        Caixa2End = new javax.swing.JTextField();
        Caixa3End = new javax.swing.JTextField();
        LogadouroEnd = new javax.swing.JLabel();
        Caixa6End = new javax.swing.JTextField();
        NumeroEnd = new javax.swing.JLabel();
        Caixa7End = new javax.swing.JTextField();
        CidadeEnd = new javax.swing.JLabel();
        Caixa8End = new javax.swing.JTextField();
        ContinuarBotao = new javax.swing.JButton();
        CarrinhoIcon = new javax.swing.JLabel();
        TituloEmpresa1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TituloEmpresa = new javax.swing.JLabel();
        TelaFundo = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Caixa2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa2);
        Caixa2.setBounds(170, 230, 460, 30);

        TituloEndereco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloEndereco.setText("Endereço");
        getContentPane().add(TituloEndereco);
        TituloEndereco.setBounds(60, 330, 240, 60);

        Telefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Telefone.setText("Telefone:");
        getContentPane().add(Telefone);
        Telefone.setBounds(60, 220, 130, 50);

        ComplementoEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComplementoEnd.setText("Complemento:");
        getContentPane().add(ComplementoEnd);
        ComplementoEnd.setBounds(60, 510, 180, 50);

        CNPJ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CNPJ.setText("CNPJ:");
        getContentPane().add(CNPJ);
        CNPJ.setBounds(60, 260, 130, 50);

        Caixa3.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa3);
        Caixa3.setBounds(140, 270, 460, 30);

        Caixa1End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa1End);
        Caixa1End.setBounds(220, 520, 480, 30);

        Nome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Nome.setText("Nome:");
        getContentPane().add(Nome);
        Nome.setBounds(60, 180, 130, 50);

        CepEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CepEnd.setText("CEP:");
        getContentPane().add(CepEnd);
        CepEnd.setBounds(590, 470, 130, 50);

        BairroEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BairroEnd.setText("Bairro:");
        getContentPane().add(BairroEnd);
        BairroEnd.setBounds(60, 430, 130, 50);

        EstadoEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EstadoEnd.setText("Estado:");
        getContentPane().add(EstadoEnd);
        EstadoEnd.setBounds(60, 470, 130, 50);

        Caixa1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa1);
        Caixa1.setBounds(140, 190, 460, 30);

        Caixa5End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa5End);
        Caixa5End.setBounds(650, 480, 270, 30);

        Caixa2End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa2End);
        Caixa2End.setBounds(140, 440, 260, 30);

        Caixa3End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa3End);
        Caixa3End.setBounds(150, 480, 260, 30);

        LogadouroEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogadouroEnd.setText("Logadouro:");
        getContentPane().add(LogadouroEnd);
        LogadouroEnd.setBounds(60, 390, 130, 50);

        Caixa6End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa6End);
        Caixa6End.setBounds(190, 400, 390, 30);

        NumeroEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NumeroEnd.setText("Número:");
        getContentPane().add(NumeroEnd);
        NumeroEnd.setBounds(590, 390, 130, 50);

        Caixa7End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa7End);
        Caixa7End.setBounds(690, 400, 150, 30);

        CidadeEnd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CidadeEnd.setText("Cidade:");
        getContentPane().add(CidadeEnd);
        CidadeEnd.setBounds(590, 430, 130, 50);

        Caixa8End.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Caixa8End);
        Caixa8End.setBounds(680, 440, 220, 30);

        ContinuarBotao.setBackground(new java.awt.Color(255, 229, 77));
        ContinuarBotao.setText("Continuar");
        getContentPane().add(ContinuarBotao);
        ContinuarBotao.setBounds(360, 590, 110, 50);

        CarrinhoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho menor.jpg"))); // NOI18N
        getContentPane().add(CarrinhoIcon);
        CarrinhoIcon.setBounds(10, 10, 210, 100);

        TituloEmpresa1.setBackground(new java.awt.Color(255, 204, 153));
        TituloEmpresa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloEmpresa1.setText("Dados da Empresa");
        getContentPane().add(TituloEmpresa1);
        TituloEmpresa1.setBounds(60, 110, 240, 60);

        jPanel1.setBackground(new java.awt.Color(255, 229, 77));

        TituloEmpresa.setBackground(new java.awt.Color(255, 204, 153));
        TituloEmpresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloEmpresa.setText("Cadastro do Supermercado");
        jPanel1.add(TituloEmpresa);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 40, 510, 40);

        TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        TelaFundo.setText("jLabel1");
        getContentPane().add(TelaFundo);
        TelaFundo.setBounds(0, 0, 940, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BairroEnd;
    private javax.swing.JLabel CNPJ;
    private javax.swing.JTextField Caixa1;
    private javax.swing.JTextField Caixa1End;
    private javax.swing.JTextField Caixa2;
    private javax.swing.JTextField Caixa2End;
    private javax.swing.JTextField Caixa3;
    private javax.swing.JTextField Caixa3End;
    private javax.swing.JTextField Caixa5End;
    private javax.swing.JTextField Caixa6End;
    private javax.swing.JTextField Caixa7End;
    private javax.swing.JTextField Caixa8End;
    private javax.swing.JLabel CarrinhoIcon;
    private javax.swing.JLabel CepEnd;
    private javax.swing.JLabel CidadeEnd;
    private javax.swing.JLabel ComplementoEnd;
    private javax.swing.JButton ContinuarBotao;
    private javax.swing.JLabel EstadoEnd;
    private javax.swing.JLabel LogadouroEnd;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel NumeroEnd;
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel TituloEmpresa;
    private javax.swing.JLabel TituloEmpresa1;
    private javax.swing.JLabel TituloEndereco;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
