/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controle.ControleCliente;
import Model.Cliente;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beatr
 */
public class MenuCliente extends javax.swing.JFrame {

    Cliente modelCliente = new Cliente();
    ControleCliente controleCliente = new ControleCliente();
    List<Cliente> listaCliente = new ArrayList<>();
    /**
     * Creates new form TelaCadUsu
     */
    public MenuCliente() {
        initComponents();
        carregarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtUsu = new javax.swing.JScrollPane();
        txtCdtUsu = new javax.swing.JTextPane();
        txtNomeUsu = new javax.swing.JTextField();
        txtEmailUsu = new javax.swing.JTextField();
        txtCPFUsu = new javax.swing.JTextField();
        txtLoginUsu = new javax.swing.JTextField();
        BarraNomeUsu = new javax.swing.JTextField();
        BarraEmailUsu = new javax.swing.JTextField();
        BarraLoginUsu = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnPesquisarCliente = new javax.swing.JButton();
        BarraCPFUsu = new javax.swing.JFormattedTextField();
        Tabela = new javax.swing.JScrollPane();
        tblcliente = new javax.swing.JTable();
        btnExcluirCliente1 = new javax.swing.JButton();
        BarraLoginUsu1 = new javax.swing.JTextField();
        btnAtuaCliente1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCdtUsu.setEditable(false);
        txtCdtUsu.setBackground(new java.awt.Color(255, 229, 77));
        txtCdtUsu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCdtUsu.setText("                      Cliente ");
        CdtUsu.setViewportView(txtCdtUsu);

        jPanel1.add(CdtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        txtNomeUsu.setEditable(false);
        txtNomeUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeUsu.setText("Nome:");
        txtNomeUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, -1));

        txtEmailUsu.setEditable(false);
        txtEmailUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailUsu.setText("E-mail:");
        txtEmailUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtEmailUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, -1));

        txtCPFUsu.setEditable(false);
        txtCPFUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtCPFUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCPFUsu.setText("CPF:");
        txtCPFUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCPFUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPFUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 50, -1));

        txtLoginUsu.setEditable(false);
        txtLoginUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtLoginUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLoginUsu.setText("Login:");
        txtLoginUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLoginUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));

        BarraNomeUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraNomeUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 360, -1));

        BarraEmailUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraEmailUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 360, -1));

        BarraLoginUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraLoginUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 190, -1));

        btnVoltar.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("");
        btnVoltar.setActionCommand("");
        btnVoltar.setBorderPainted(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        btnPesquisarCliente.setBackground(new java.awt.Color(255, 229, 77));
        btnPesquisarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.setToolTipText("");
        btnPesquisarCliente.setActionCommand("");
        btnPesquisarCliente.setBorderPainted(false);
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 90, 20));

        BarraCPFUsu.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraCPFUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(BarraCPFUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, -1));

        tblcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblcliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "E-mail", "CPF", "Login"
            }
        ));
        Tabela.setViewportView(tblcliente);

        jPanel1.add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 620, 150));

        btnExcluirCliente1.setBackground(new java.awt.Color(255, 229, 77));
        btnExcluirCliente1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirCliente1.setText("Excluir");
        btnExcluirCliente1.setToolTipText("");
        btnExcluirCliente1.setActionCommand("");
        btnExcluirCliente1.setBorderPainted(false);
        btnExcluirCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, 20));

        BarraLoginUsu1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraLoginUsu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, -1));

        btnAtuaCliente1.setBackground(new java.awt.Color(255, 229, 77));
        btnAtuaCliente1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtuaCliente1.setText("Atualizar");
        btnAtuaCliente1.setToolTipText("");
        btnAtuaCliente1.setActionCommand("");
        btnAtuaCliente1.setBorderPainted(false);
        btnAtuaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtuaCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtuaCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFUsuActionPerformed

    private void txtLoginUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsuActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        // TODO add your handling code here:
        modelCliente = new Cliente();
        modelCliente.setUsuNome(BarraNomeUsu.getText());
        modelCliente.setUsuEmail(BarraEmailUsu.getText());
        modelCliente.setUsuCPF(BarraCPFUsu.getText());
        modelCliente.setUsuLogin(BarraLoginUsu.getText());
        controleCliente.salvarClienteControle(modelCliente);
        formularioUsuVazio();
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void formularioUsuVazio(){
        if((BarraNomeUsu.getText().length() > 0) 
                && (BarraCPFUsu.getText().length() > 0)
                && (BarraEmailUsu.getText().length() > 0)
                && (BarraLoginUsu.getText().length() > 0)){
            JOptionPane.showMessageDialog(this, "Cadastro realizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            limparFormularioUsu();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Erro", JOptionPane.ERROR_MESSAGE);
        }        
    }    
    /**
     * Limpar formúlario de cadastro de usuários
     * @param void 
     */
    private void limparFormularioUsu(){
        BarraNomeUsu.setText("");
        BarraEmailUsu.setText("");
        BarraCPFUsu.setText("");
        BarraLoginUsu.setText("");        
    }
    
    /**
     * Carregar lista de clientes na tabela 
     */
    private void carregarCliente(){
        listaCliente = controleCliente.getListaClienteControle();
        DefaultTableModel modelo2 = (DefaultTableModel) tblcliente.getModel();
        modelo2.setNumRows(0);
        
        for (int i = 0; i < listaCliente.size(); i++) {
            modelo2.addRow(new Object[]{
                listaCliente.get(i).getUsuId(),
                listaCliente.get(i).getUsuNome(),
                listaCliente.get(i).getUsuEmail(),
                listaCliente.get(i).getUsuCPF(),
                listaCliente.get(i).getUsuLogin()
            });
        }
    }
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaTipCad objeto5 = new TelaTipCad();
        objeto5.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirCliente1ActionPerformed

    private void btnAtuaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuaCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtuaCliente1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BarraCPFUsu;
    private javax.swing.JTextField BarraEmailUsu;
    private javax.swing.JTextField BarraLoginUsu;
    private javax.swing.JTextField BarraLoginUsu1;
    private javax.swing.JTextField BarraNomeUsu;
    private javax.swing.JScrollPane CdtUsu;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JButton btnAtuaCliente1;
    private javax.swing.JButton btnExcluirCliente1;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblcliente;
    private javax.swing.JTextField txtCPFUsu;
    private javax.swing.JTextPane txtCdtUsu;
    private javax.swing.JTextField txtEmailUsu;
    private javax.swing.JTextField txtLoginUsu;
    private javax.swing.JTextField txtNomeUsu;
    // End of variables declaration//GEN-END:variables
}
