/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controle.ControleCliente;
import DAO.DAOCliente;
import Model.Cliente;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beatr
 */
public class MenuCliente extends javax.swing.JFrame {

    Cliente modelCliente = new Cliente();
    ControleCliente controleCliente = new ControleCliente();
    List<Cliente> listaCliente = new ArrayList<>();
    /**
     * Creates new form TelaCadUsu
     */
    public MenuCliente() {
        initComponents();
        carregarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtUsu = new javax.swing.JScrollPane();
        txtCdtUsu = new javax.swing.JTextPane();
        txtCodigoUsu = new javax.swing.JTextField();
        txtEmailUsu = new javax.swing.JTextField();
        txtCPFUsu = new javax.swing.JTextField();
        txtLoginUsu = new javax.swing.JTextField();
        BarraCodigoUsu = new javax.swing.JTextField();
        BarraEmailUsu = new javax.swing.JTextField();
        BarraPesquisaUsu = new javax.swing.JTextField();
        btnSairCliente = new javax.swing.JButton();
        btnSalvarCliente = new javax.swing.JButton();
        BarraCPFUsu = new javax.swing.JFormattedTextField();
        Tabela = new javax.swing.JScrollPane();
        tblcliente = new javax.swing.JTable();
        btnPesquisaCliente = new javax.swing.JButton();
        btnAtuaCliente1 = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        btnExcluirCliente2 = new javax.swing.JButton();
        txtNomeUsu1 = new javax.swing.JTextField();
        BarraNomeUsu1 = new javax.swing.JTextField();
        btnLimpaCliente1 = new javax.swing.JButton();
        txtLoginUsu1 = new javax.swing.JTextField();
        BarraLoginUsu = new javax.swing.JTextField();
        BarraSenhaUsu1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Cliente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCdtUsu.setEditable(false);
        txtCdtUsu.setBackground(new java.awt.Color(255, 229, 77));
        txtCdtUsu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCdtUsu.setText("                      Cliente ");
        CdtUsu.setViewportView(txtCdtUsu);

        jPanel1.add(CdtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        txtCodigoUsu.setEditable(false);
        txtCodigoUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigoUsu.setText("Código:");
        txtCodigoUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtCodigoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));

        txtEmailUsu.setEditable(false);
        txtEmailUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailUsu.setText("E-mail:");
        txtEmailUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtEmailUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, -1));

        txtCPFUsu.setEditable(false);
        txtCPFUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtCPFUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCPFUsu.setText("CPF:");
        txtCPFUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCPFUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPFUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 50, -1));

        txtLoginUsu.setEditable(false);
        txtLoginUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtLoginUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLoginUsu.setText("Senha:");
        txtLoginUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLoginUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, -1));

        BarraCodigoUsu.setEditable(false);
        BarraCodigoUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraCodigoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 360, -1));

        BarraEmailUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraEmailUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 360, -1));

        BarraPesquisaUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraPesquisaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 190, -1));

        btnSairCliente.setBackground(new java.awt.Color(255, 229, 77));
        btnSairCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSairCliente.setText("Sair");
        btnSairCliente.setToolTipText("");
        btnSairCliente.setActionCommand("");
        btnSairCliente.setBorderPainted(false);
        btnSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSairCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 80, 20));

        btnSalvarCliente.setBackground(new java.awt.Color(255, 229, 77));
        btnSalvarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.setToolTipText("");
        btnSalvarCliente.setActionCommand("");
        btnSalvarCliente.setBorderPainted(false);
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 80, 20));

        BarraCPFUsu.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraCPFUsu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(BarraCPFUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, -1));

        tblcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblcliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "E-mail", "CPF", "Login"
            }
        ));
        Tabela.setViewportView(tblcliente);

        jPanel1.add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 620, 190));

        btnPesquisaCliente.setBackground(new java.awt.Color(255, 229, 77));
        btnPesquisaCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisaCliente.setText("Pesquisar");
        btnPesquisaCliente.setToolTipText("");
        btnPesquisaCliente.setActionCommand("");
        btnPesquisaCliente.setBorderPainted(false);
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 90, 20));

        btnAtuaCliente1.setBackground(new java.awt.Color(255, 229, 77));
        btnAtuaCliente1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtuaCliente1.setText("Exibir informações");
        btnAtuaCliente1.setToolTipText("");
        btnAtuaCliente1.setActionCommand("");
        btnAtuaCliente1.setBorderPainted(false);
        btnAtuaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtuaCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtuaCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, 20));

        btnVoltar1.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.setToolTipText("");
        btnVoltar1.setActionCommand("");
        btnVoltar1.setBorderPainted(false);
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        btnExcluirCliente2.setBackground(new java.awt.Color(255, 229, 77));
        btnExcluirCliente2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirCliente2.setText("Excluir");
        btnExcluirCliente2.setToolTipText("");
        btnExcluirCliente2.setActionCommand("");
        btnExcluirCliente2.setBorderPainted(false);
        btnExcluirCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCliente2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 80, 20));

        txtNomeUsu1.setEditable(false);
        txtNomeUsu1.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeUsu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeUsu1.setText("Nome:");
        txtNomeUsu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeUsu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, -1));

        BarraNomeUsu1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraNomeUsu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 360, -1));

        btnLimpaCliente1.setBackground(new java.awt.Color(255, 229, 77));
        btnLimpaCliente1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpaCliente1.setText("Limpar");
        btnLimpaCliente1.setToolTipText("");
        btnLimpaCliente1.setActionCommand("");
        btnLimpaCliente1.setBorderPainted(false);
        btnLimpaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpaCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 80, 20));

        txtLoginUsu1.setEditable(false);
        txtLoginUsu1.setBackground(new java.awt.Color(255, 255, 255));
        txtLoginUsu1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLoginUsu1.setText("Login:");
        txtLoginUsu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLoginUsu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsu1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginUsu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));

        BarraLoginUsu.setBackground(new java.awt.Color(204, 204, 204));
        BarraLoginUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraLoginUsuActionPerformed(evt);
            }
        });
        jPanel1.add(BarraLoginUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, -1));

        BarraSenhaUsu1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraSenhaUsu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFUsuActionPerformed

    private void txtLoginUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsuActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        // TODO add your handling code here:
        modelCliente = new Cliente();
        modelCliente.setUsuNome(BarraNomeUsu1.getText());
        modelCliente.setUsuEmail(BarraEmailUsu.getText());
        modelCliente.setUsuCPF(BarraCPFUsu.getText());
        modelCliente.setUsuLogin(BarraLoginUsu.getText());
        modelCliente.setUsuSenha(String.valueOf(BarraSenhaUsu1.getPassword()));
        controleCliente.salvarClienteControle(modelCliente);
        formularioUsuVazio();
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void formularioUsuVazio(){
        if((BarraNomeUsu1.getText().length() > 0) 
                && (BarraCPFUsu.getText().length() > 0)
                && (BarraEmailUsu.getText().length() > 0)
                && (BarraLoginUsu.getText().length() > 0)){
            JOptionPane.showMessageDialog(this, "Cadastro realizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            limparFormularioUsu();
            carregarCliente();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Erro", JOptionPane.ERROR_MESSAGE);
        }        
    }    
    /**
     * Limpar formúlario de cadastro de usuários
     * @param void 
     */
    private void limparFormularioUsu(){
        BarraCodigoUsu.setText("");
        BarraNomeUsu1.setText("");
        BarraEmailUsu.setText("");
        BarraCPFUsu.setText("");
        BarraLoginUsu.setText("");
        BarraSenhaUsu1.setText("");
    }
    
    /**
     * Carregar lista de clientes na tabela 
     */
    private void carregarCliente(){
        listaCliente = controleCliente.getListaClienteControle();
        DefaultTableModel modelo2 = (DefaultTableModel) tblcliente.getModel();
        modelo2.setNumRows(0);
        
        for (int i = 0; i < listaCliente.size(); i++) {
            modelo2.addRow(new Object[]{
                listaCliente.get(i).getUsuId(),
                listaCliente.get(i).getUsuNome(),
                listaCliente.get(i).getUsuEmail(),
                listaCliente.get(i).getUsuCPF(),
                listaCliente.get(i).getUsuLogin(),
            });
        }
    }
    
    private void btnSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairClienteActionPerformed
        // TODO add your handling code here:
        TelaLogin objeto5 = new TelaLogin();
        objeto5.setVisible(true);
    }//GEN-LAST:event_btnSairClienteActionPerformed

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        // TODO add your handling code here:        
        pesquisarCliente(BarraPesquisaUsu.getText());
        
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed
    
    private void pesquisarCliente(String nome){
        DefaultTableModel modelo2 = (DefaultTableModel) tblcliente.getModel();
        modelo2.setNumRows(0);
        DAOCliente pdao = new DAOCliente();
       
        for(Cliente c: pdao.readForNome(nome)){
           
            modelo2.addRow(new Object[]{
                c.getUsuId(),
                c.getUsuNome(),
                c.getUsuEmail(),
                c.getUsuCPF(),
                c.getUsuLogin()
           });
       }

    }          
    
    private void btnAtuaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuaCliente1ActionPerformed
        // Pegar o id e buscar noo banco
        modelCliente = new Cliente();
        int linha = tblcliente.getSelectedRow();
        if (linha <0) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }else{
            int codigo = (int) tblcliente.getValueAt(linha, 0);
            modelCliente = controleCliente.getClienteControle(codigo);
            BarraCodigoUsu.setText(String.valueOf(modelCliente.getUsuId()));
            BarraNomeUsu1.setText(modelCliente.getUsuNome());
            BarraEmailUsu.setText(modelCliente.getUsuEmail());
            BarraCPFUsu.setText(modelCliente.getUsuCPF());
            BarraLoginUsu.setText(modelCliente.getUsuLogin());
            BarraSenhaUsu1.setText(modelCliente.getUsuSenha());        
            
            
            
            //JOptionPane.showMessageDialog(this, "Cliente atualizado!");
        }        
    }//GEN-LAST:event_btnAtuaCliente1ActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        TelaTipCad objeto1 = new TelaTipCad();
        objeto1.setVisible(true);
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnExcluirCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCliente2ActionPerformed
        // TODO add your handling code here:
        int linha = tblcliente.getSelectedRow();
        if (linha <0) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }else{
            int codigo = (int) tblcliente.getValueAt(linha, 0);
            controleCliente.excluirClienteControle(codigo);
            carregarCliente();
            limparFormularioUsu();
            JOptionPane.showMessageDialog(this, "Cliente excluido!");
        }
    }//GEN-LAST:event_btnExcluirCliente2ActionPerformed

    private void btnLimpaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaCliente1ActionPerformed
        // TODO add your handling code here:
        limparFormularioUsu();
    }//GEN-LAST:event_btnLimpaCliente1ActionPerformed

    private void txtLoginUsu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsu1ActionPerformed

    private void BarraLoginUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraLoginUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraLoginUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BarraCPFUsu;
    private javax.swing.JTextField BarraCodigoUsu;
    private javax.swing.JTextField BarraEmailUsu;
    private javax.swing.JTextField BarraLoginUsu;
    private javax.swing.JTextField BarraNomeUsu1;
    private javax.swing.JTextField BarraPesquisaUsu;
    private javax.swing.JPasswordField BarraSenhaUsu1;
    private javax.swing.JScrollPane CdtUsu;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JButton btnAtuaCliente1;
    private javax.swing.JButton btnExcluirCliente2;
    private javax.swing.JButton btnLimpaCliente1;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnSairCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblcliente;
    private javax.swing.JTextField txtCPFUsu;
    private javax.swing.JTextPane txtCdtUsu;
    private javax.swing.JTextField txtCodigoUsu;
    private javax.swing.JTextField txtEmailUsu;
    private javax.swing.JTextField txtLoginUsu;
    private javax.swing.JTextField txtLoginUsu1;
    private javax.swing.JTextField txtNomeUsu1;
    // End of variables declaration//GEN-END:variables
}
