/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controle.ControleEmpresa;
import Model.Empresa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author beatr
 */
public class TabelaEndereco extends javax.swing.JFrame {

    Empresa modelEmpresa = new Empresa();
    ControleEmpresa controleEmpresa = new ControleEmpresa();
    List<Empresa> listaEmpresa = new ArrayList<>();
    
    
    /**
     * Creates new form TelaCadUsu
     */
    public TabelaEndereco() {
        initComponents();
        carregarEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtEmp = new javax.swing.JScrollPane();
        txtCadEmp = new javax.swing.JTextPane();
        txtEmailEmp = new javax.swing.JTextField();
        txtFoneEmp = new javax.swing.JTextField();
        BarraCidade = new javax.swing.JTextField();
        BarraEmailEmp = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        txtDadoEmp = new javax.swing.JTextField();
        txtNomeEmp = new javax.swing.JTextField();
        BarraNomeEmp = new javax.swing.JTextField();
        txtCidadeEmp = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        BarraBairro = new javax.swing.JTextField();
        UF = new javax.swing.JTextField();
        BarraUF = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        BarraEndereco = new javax.swing.JTextField();
        btnVoltarTip = new javax.swing.JButton();
        btnPesquisaEmp = new javax.swing.JButton();
        txtNumeroEmp = new javax.swing.JTextField();
        BarraFoneEmp = new javax.swing.JFormattedTextField();
        BarraCnpj = new javax.swing.JFormattedTextField();
        BarraNumero = new javax.swing.JTextField();
        Tabela = new javax.swing.JScrollPane();
        tblPesquisaEmp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadEmp.setEditable(false);
        txtCadEmp.setBackground(new java.awt.Color(255, 229, 77));
        txtCadEmp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCadEmp.setText("          Pesquisar Empresa ");
        CdtEmp.setViewportView(txtCadEmp);

        jPanel1.add(CdtEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        txtEmailEmp.setEditable(false);
        txtEmailEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailEmp.setText("E-mail:");
        txtEmailEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, -1));

        txtFoneEmp.setEditable(false);
        txtFoneEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtFoneEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFoneEmp.setText("Telefone:");
        txtFoneEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtFoneEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoneEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtFoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, -1));

        BarraCidade.setBackground(new java.awt.Color(204, 204, 204));
        BarraCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 140, -1));

        BarraEmailEmp.setBackground(new java.awt.Color(204, 204, 204));
        BarraEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraEmailEmpActionPerformed(evt);
            }
        });
        jPanel1.add(BarraEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 360, -1));

        txtCNPJ.setEditable(false);
        txtCNPJ.setBackground(new java.awt.Color(255, 255, 255));
        txtCNPJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCNPJ.setText("CNPJ:");
        txtCNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });
        jPanel1.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 50, -1));

        txtDadoEmp.setEditable(false);
        txtDadoEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtDadoEmp.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        txtDadoEmp.setText("Dados da Empresa");
        txtDadoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtDadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 150, -1));

        txtNomeEmp.setEditable(false);
        txtNomeEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeEmp.setText("Nome:");
        txtNomeEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, -1));

        BarraNomeEmp.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 360, -1));

        txtCidadeEmp.setEditable(false);
        txtCidadeEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtCidadeEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCidadeEmp.setText("Cidade:");
        txtCidadeEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtCidadeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 50, -1));

        txtBairro.setEditable(false);
        txtBairro.setBackground(new java.awt.Color(255, 255, 255));
        txtBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBairro.setText("Bairro:");
        txtBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, -1));

        BarraBairro.setBackground(new java.awt.Color(204, 204, 204));
        BarraBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraBairroActionPerformed(evt);
            }
        });
        jPanel1.add(BarraBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, -1));

        UF.setEditable(false);
        UF.setBackground(new java.awt.Color(255, 255, 255));
        UF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UF.setText("UF:");
        UF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFActionPerformed(evt);
            }
        });
        jPanel1.add(UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 30, -1));

        BarraUF.setBackground(new java.awt.Color(204, 204, 204));
        BarraUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraUFActionPerformed(evt);
            }
        });
        jPanel1.add(BarraUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 60, -1));

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEndereco.setText("Endereço:");
        txtEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, -1));

        BarraEndereco.setBackground(new java.awt.Color(204, 204, 204));
        BarraEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(BarraEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 360, -1));

        btnVoltarTip.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltarTip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltarTip.setText("Voltar");
        btnVoltarTip.setToolTipText("");
        btnVoltarTip.setActionCommand("");
        btnVoltarTip.setBorderPainted(false);
        btnVoltarTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTipActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        btnPesquisaEmp.setBackground(new java.awt.Color(255, 229, 77));
        btnPesquisaEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisaEmp.setText("Pesquisa");
        btnPesquisaEmp.setToolTipText("");
        btnPesquisaEmp.setActionCommand("");
        btnPesquisaEmp.setBorderPainted(false);
        btnPesquisaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisaEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 150, 20));

        txtNumeroEmp.setEditable(false);
        txtNumeroEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNumeroEmp.setText("Nº:");
        txtNumeroEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNumeroEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 30, -1));

        BarraFoneEmp.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraFoneEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(BarraFoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 240, -1));

        BarraCnpj.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##. ###. ###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BarraCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCnpjActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 250, -1));

        BarraNumero.setBackground(new java.awt.Color(204, 204, 204));
        BarraNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(BarraNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 60, -1));

        tblPesquisaEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPesquisaEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblPesquisaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "E-mail", "Telefone", "CNPJ", "Endereço", "Bairro", "Cidade", "Nº", "UF"
            }
        ));
        Tabela.setViewportView(tblPesquisaEmp);

        jPanel1.add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 680, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFoneEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoneEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoneEmpActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void BarraCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCidadeActionPerformed

    private void BarraBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraBairroActionPerformed

    private void UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFActionPerformed

    private void BarraUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraUFActionPerformed

    private void BarraEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraEnderecoActionPerformed

    private void btnPesquisaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmpActionPerformed
        // TODO add your handling code here:
        limparFormularioEmp(); //Depois de finalizar a pesquisar limpar o formúlario
    }//GEN-LAST:event_btnPesquisaEmpActionPerformed
    
    /**
     * Limpar formúlario de cadastro de empresa
     * @param void 
     */
    private void limparFormularioEmp(){
        BarraNomeEmp.setText("");
        BarraEmailEmp.setText("");
        BarraFoneEmp.setText("");
        BarraCnpj.setText("");
        BarraEndereco.setText("");
        BarraBairro.setText("");
        BarraCidade.setText("");
        BarraNumero.setText("");
        BarraUF.setText("");        
    }
    
    private void carregarEmpresa(){
        listaEmpresa = controleEmpresa.getListaEmpresaControle();
        DefaultTableModel modelo4 = (DefaultTableModel) tblPesquisaEmp.getModel();
        modelo4.setNumRows(0);
        
        for (int i = 0; i < listaEmpresa.size(); i++){
            modelo4.addRow(new Object[]{
                listaEmpresa.get(i).getEmpId(),
                listaEmpresa.get(i).getEmpNome(),
                listaEmpresa.get(i).getEmpEmail(),
                listaEmpresa.get(i).getEmpFone(),
                listaEmpresa.get(i).getEmpCNPJ(),
                listaEmpresa.get(i).getEmpEnd(),
                listaEmpresa.get(i).getEmpBairro(),
                listaEmpresa.get(i).getEmpCidade(),
                listaEmpresa.get(i).getEmpNumero(),
                listaEmpresa.get(i).getEmpEstado(),
            });
        }
    }
    
    private void btnVoltarTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTipActionPerformed
        // TODO add your handling code here:
        TelaTipCad objeto5 = new TelaTipCad();
        objeto5.setVisible(true);
    }//GEN-LAST:event_btnVoltarTipActionPerformed

    private void txtNumeroEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEmpActionPerformed

    private void BarraCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCnpjActionPerformed

    private void BarraNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraNumeroActionPerformed

    private void txtEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEmpActionPerformed

    private void BarraEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraEmailEmpActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBairro;
    private javax.swing.JTextField BarraCidade;
    private javax.swing.JFormattedTextField BarraCnpj;
    private javax.swing.JTextField BarraEmailEmp;
    private javax.swing.JTextField BarraEndereco;
    private javax.swing.JFormattedTextField BarraFoneEmp;
    private javax.swing.JTextField BarraNomeEmp;
    private javax.swing.JTextField BarraNumero;
    private javax.swing.JTextField BarraUF;
    private javax.swing.JScrollPane CdtEmp;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JTextField UF;
    private javax.swing.JButton btnPesquisaEmp;
    private javax.swing.JButton btnVoltarTip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblPesquisaEmp;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextPane txtCadEmp;
    private javax.swing.JTextField txtCidadeEmp;
    private javax.swing.JTextField txtDadoEmp;
    private javax.swing.JTextField txtEmailEmp;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFoneEmp;
    private javax.swing.JTextField txtNomeEmp;
    private javax.swing.JTextField txtNumeroEmp;
    // End of variables declaration//GEN-END:variables
}
