/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controle.ControleEmpresa;
import DAO.DAOEmpresa;
import Model.Empresa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author beatr
 */
public class TabEndereco extends javax.swing.JFrame {

    Empresa modelEmpresa = new Empresa();
    ControleEmpresa controleEmpresa = new ControleEmpresa();
    List<Empresa> listaEmpresa = new ArrayList<>();
    
    
    /**
     * Creates new form TelaCadUsu
     */
    public TabEndereco() {
        initComponents();
        carregarEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtEmp = new javax.swing.JScrollPane();
        txtCadEmp = new javax.swing.JTextPane();
        txtEmailEmp = new javax.swing.JTextField();
        txtFoneEmp = new javax.swing.JTextField();
        BarraCidade = new javax.swing.JTextField();
        BarraNomeEmp = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        txtDadoEmp = new javax.swing.JTextField();
        txtCodigoEmp = new javax.swing.JTextField();
        BarraEmailEmp = new javax.swing.JTextField();
        txtCidadeEmp = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        BarraBairro = new javax.swing.JTextField();
        UF = new javax.swing.JTextField();
        BarraUF = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        BarraEndereco = new javax.swing.JTextField();
        btnVoltarTip = new javax.swing.JButton();
        btnSairLocEmp = new javax.swing.JButton();
        txtNumeroEmp = new javax.swing.JTextField();
        BarraFoneEmp = new javax.swing.JFormattedTextField();
        BarraCnpj = new javax.swing.JFormattedTextField();
        BarraNumero = new javax.swing.JTextField();
        Tabela = new javax.swing.JScrollPane();
        tblPesquisaEmp = new javax.swing.JTable();
        BarraPesEndEMp = new javax.swing.JTextField();
        btnPesquisaEmp1 = new javax.swing.JButton();
        btnExibirInfEmp1 = new javax.swing.JButton();
        txtNomeEmp1 = new javax.swing.JTextField();
        BarraCodEmp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Localizar Empresa");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadEmp.setEditable(false);
        txtCadEmp.setBackground(new java.awt.Color(255, 229, 77));
        txtCadEmp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCadEmp.setText("            Localizar Empresa ");
        CdtEmp.setViewportView(txtCadEmp);

        jPanel1.add(CdtEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 330, 40));

        txtEmailEmp.setEditable(false);
        txtEmailEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailEmp.setText("E-mail:");
        txtEmailEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, -1));

        txtFoneEmp.setEditable(false);
        txtFoneEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtFoneEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFoneEmp.setText("Telefone:");
        txtFoneEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtFoneEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoneEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtFoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 60, -1));

        BarraCidade.setBackground(new java.awt.Color(204, 204, 204));
        BarraCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 140, -1));

        BarraNomeEmp.setBackground(new java.awt.Color(204, 204, 204));
        BarraNomeEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraNomeEmpActionPerformed(evt);
            }
        });
        jPanel1.add(BarraNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 360, -1));

        txtCNPJ.setEditable(false);
        txtCNPJ.setBackground(new java.awt.Color(255, 255, 255));
        txtCNPJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCNPJ.setText("CNPJ:");
        txtCNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });
        jPanel1.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 50, -1));

        txtDadoEmp.setEditable(false);
        txtDadoEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtDadoEmp.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        txtDadoEmp.setText("Dados da Empresa");
        txtDadoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtDadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, -1));

        txtCodigoEmp.setEditable(false);
        txtCodigoEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigoEmp.setText("Código:");
        txtCodigoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtCodigoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 50, -1));

        BarraEmailEmp.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 360, -1));

        txtCidadeEmp.setEditable(false);
        txtCidadeEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtCidadeEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCidadeEmp.setText("Cidade:");
        txtCidadeEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtCidadeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 50, -1));

        txtBairro.setEditable(false);
        txtBairro.setBackground(new java.awt.Color(255, 255, 255));
        txtBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBairro.setText("Bairro:");
        txtBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 50, -1));

        BarraBairro.setBackground(new java.awt.Color(204, 204, 204));
        BarraBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraBairroActionPerformed(evt);
            }
        });
        jPanel1.add(BarraBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 170, -1));

        UF.setEditable(false);
        UF.setBackground(new java.awt.Color(255, 255, 255));
        UF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UF.setText("UF:");
        UF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFActionPerformed(evt);
            }
        });
        jPanel1.add(UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 30, -1));

        BarraUF.setBackground(new java.awt.Color(204, 204, 204));
        BarraUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraUFActionPerformed(evt);
            }
        });
        jPanel1.add(BarraUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 60, -1));

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEndereco.setText("Endereço:");
        txtEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 70, -1));

        BarraEndereco.setBackground(new java.awt.Color(204, 204, 204));
        BarraEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(BarraEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 360, -1));

        btnVoltarTip.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltarTip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltarTip.setText("Voltar");
        btnVoltarTip.setToolTipText("");
        btnVoltarTip.setActionCommand("");
        btnVoltarTip.setBorderPainted(false);
        btnVoltarTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTipActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        btnSairLocEmp.setBackground(new java.awt.Color(255, 229, 77));
        btnSairLocEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSairLocEmp.setText("Sair");
        btnSairLocEmp.setToolTipText("");
        btnSairLocEmp.setActionCommand("");
        btnSairLocEmp.setBorderPainted(false);
        btnSairLocEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairLocEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSairLocEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 80, 20));

        txtNumeroEmp.setEditable(false);
        txtNumeroEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNumeroEmp.setText("Nº:");
        txtNumeroEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNumeroEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 30, 20));

        BarraFoneEmp.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraFoneEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(BarraFoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 240, -1));

        BarraCnpj.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##. ###. ###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BarraCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCnpjActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 250, -1));

        BarraNumero.setBackground(new java.awt.Color(204, 204, 204));
        BarraNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(BarraNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 60, -1));

        tblPesquisaEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPesquisaEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblPesquisaEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "E-mail", "Telefone", "CNPJ", "Endereço", "Bairro", "Cidade", "Nº", "UF"
            }
        ));
        Tabela.setViewportView(tblPesquisaEmp);

        jPanel1.add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 680, 170));

        BarraPesEndEMp.setBackground(new java.awt.Color(204, 204, 204));
        BarraPesEndEMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPesEndEMpActionPerformed(evt);
            }
        });
        jPanel1.add(BarraPesEndEMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 450, -1));

        btnPesquisaEmp1.setBackground(new java.awt.Color(255, 229, 77));
        btnPesquisaEmp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisaEmp1.setText("Pesquisa");
        btnPesquisaEmp1.setToolTipText("");
        btnPesquisaEmp1.setActionCommand("");
        btnPesquisaEmp1.setBorderPainted(false);
        btnPesquisaEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisaEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 150, 20));

        btnExibirInfEmp1.setBackground(new java.awt.Color(255, 229, 77));
        btnExibirInfEmp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExibirInfEmp1.setText("Exibir informações");
        btnExibirInfEmp1.setToolTipText("");
        btnExibirInfEmp1.setActionCommand("");
        btnExibirInfEmp1.setBorderPainted(false);
        btnExibirInfEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirInfEmp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExibirInfEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, 20));

        txtNomeEmp1.setEditable(false);
        txtNomeEmp1.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeEmp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeEmp1.setText("Nome:");
        txtNomeEmp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 50, -1));

        BarraCodEmp.setBackground(new java.awt.Color(204, 204, 204));
        BarraCodEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCodEmpActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCodEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFoneEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoneEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoneEmpActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void BarraCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCidadeActionPerformed

    private void BarraBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraBairroActionPerformed

    private void UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFActionPerformed

    private void BarraUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraUFActionPerformed

    private void BarraEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraEnderecoActionPerformed

    private void btnSairLocEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairLocEmpActionPerformed
        // TODO add your handling code here:
        TelaLogin objeto5 = new TelaLogin();
        objeto5.setVisible(true);
    }//GEN-LAST:event_btnSairLocEmpActionPerformed
    
//    /**
//     * Limpar formúlario de cadastro de empresa
//     * @param void 
//     */
//    private void limparFormularioEmp(){
//        BarraEmailEmp.setText("");
//        BarraNomeEmp.setText("");
//        BarraFoneEmp.setText("");
//        BarraCnpj.setText("");
//        BarraEndereco.setText("");
//        BarraBairro.setText("");
//        BarraCidade.setText("");
//        BarraNumero.setText("");
//        BarraUF.setText("");        
//    }
    
    private void carregarEmpresa(){
        listaEmpresa = controleEmpresa.getListaEmpresaControle();
        DefaultTableModel modelo4 = (DefaultTableModel) tblPesquisaEmp.getModel();
        modelo4.setNumRows(0);
        
        for (int i = 0; i < listaEmpresa.size(); i++){
            modelo4.addRow(new Object[]{
                listaEmpresa.get(i).getEmpId(),
                listaEmpresa.get(i).getEmpNome(),
                listaEmpresa.get(i).getEmpEmail(),
                listaEmpresa.get(i).getEmpFone(),
                listaEmpresa.get(i).getEmpCNPJ(),
                listaEmpresa.get(i).getEmpEnd(),
                listaEmpresa.get(i).getEmpBairro(),
                listaEmpresa.get(i).getEmpCidade(),
                listaEmpresa.get(i).getEmpNumero(),
                listaEmpresa.get(i).getEmpEstado(),
            });
        }
    }
    
    private void btnVoltarTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTipActionPerformed
        // TODO add your handling code here:
        TelaTipCad objeto5 = new TelaTipCad();
        objeto5.setVisible(true);
    }//GEN-LAST:event_btnVoltarTipActionPerformed

    private void txtNumeroEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEmpActionPerformed

    private void BarraCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCnpjActionPerformed

    private void BarraNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraNumeroActionPerformed

    private void txtEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEmpActionPerformed

    private void BarraNomeEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraNomeEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraNomeEmpActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnPesquisaEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmp1ActionPerformed
        // TODO add your handling code here:
        pesquisarEmpresa(BarraPesEndEMp.getText());
        
    }//GEN-LAST:event_btnPesquisaEmp1ActionPerformed
    
        private void pesquisarEmpresa(String empresa){
        DefaultTableModel modelo3 = (DefaultTableModel) tblPesquisaEmp.getModel();
        modelo3.setNumRows(0);
        DAOEmpresa pdao = new DAOEmpresa();
       
        for(Empresa e: pdao.readForEmpresa(empresa)){
           
            modelo3.addRow(new Object[]{
                e.getEmpId(),
                e.getEmpNome(),
                e.getEmpEmail(),
                e.getEmpFone(),
                e.getEmpCNPJ(),
                e.getEmpEnd(),
                e.getEmpBairro(),
                e.getEmpCidade(),
                e.getEmpNumero(),
                e.getEmpEstado()
           });
       }

    }          
    
    
    private void btnExibirInfEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirInfEmp1ActionPerformed
        // TODO add your handling code here:
        modelEmpresa = new Empresa();
        int linha = tblPesquisaEmp.getSelectedRow();
        if (linha <0) {
            JOptionPane.showMessageDialog(this, "Selecione uma empresa!");
        }else{
            int codigo = (int) tblPesquisaEmp.getValueAt(linha, 0);
            modelEmpresa = controleEmpresa.getEmpresaControle(codigo);
            BarraCodEmp.setText(String.valueOf(modelEmpresa.getEmpId()));
            BarraNomeEmp.setText(modelEmpresa.getEmpNome());
            BarraEmailEmp.setText(modelEmpresa.getEmpEmail());
            BarraFoneEmp.setText(modelEmpresa.getEmpFone());
            BarraCnpj.setText(modelEmpresa.getEmpCNPJ());
            BarraEndereco.setText(modelEmpresa.getEmpEnd());
            BarraBairro.setText(modelEmpresa.getEmpBairro());
            BarraCidade.setText(modelEmpresa.getEmpCidade());
            BarraNumero.setText(modelEmpresa.getEmpNumero());
            BarraUF.setText(modelEmpresa.getEmpEstado());        
                    
        }
    }//GEN-LAST:event_btnExibirInfEmp1ActionPerformed

    private void BarraPesEndEMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPesEndEMpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPesEndEMpActionPerformed

    private void BarraCodEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCodEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCodEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBairro;
    private javax.swing.JTextField BarraCidade;
    private javax.swing.JFormattedTextField BarraCnpj;
    private javax.swing.JTextField BarraCodEmp;
    private javax.swing.JTextField BarraEmailEmp;
    private javax.swing.JTextField BarraEndereco;
    private javax.swing.JFormattedTextField BarraFoneEmp;
    private javax.swing.JTextField BarraNomeEmp;
    private javax.swing.JTextField BarraNumero;
    private javax.swing.JTextField BarraPesEndEMp;
    private javax.swing.JTextField BarraUF;
    private javax.swing.JScrollPane CdtEmp;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JTextField UF;
    private javax.swing.JButton btnExibirInfEmp1;
    private javax.swing.JButton btnPesquisaEmp1;
    private javax.swing.JButton btnSairLocEmp;
    private javax.swing.JButton btnVoltarTip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblPesquisaEmp;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextPane txtCadEmp;
    private javax.swing.JTextField txtCidadeEmp;
    private javax.swing.JTextField txtCodigoEmp;
    private javax.swing.JTextField txtDadoEmp;
    private javax.swing.JTextField txtEmailEmp;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFoneEmp;
    private javax.swing.JTextField txtNomeEmp1;
    private javax.swing.JTextField txtNumeroEmp;
    // End of variables declaration//GEN-END:variables
}
