/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author beatr
 */
public class TelaCadProd extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtProdut = new javax.swing.JScrollPane();
        txtCadProdut = new javax.swing.JTextPane();
        Produto = new javax.swing.JTextField();
        Codigo = new javax.swing.JTextField();
        Marca = new javax.swing.JTextField();
        BarraProduto = new javax.swing.JTextField();
        BarraMarca = new javax.swing.JTextField();
        BarraPreco = new javax.swing.JTextField();
        btnSair = new java.awt.Button();
        btnSalvar = new java.awt.Button();
        Tabela = new javax.swing.JScrollPane();
        TabProd = new javax.swing.JTable();
        BarraCodigo = new javax.swing.JTextField();
        btnExcluir = new java.awt.Button();
        btnEditar = new java.awt.Button();
        btnNovo = new java.awt.Button();
        Preco = new javax.swing.JTextField();
        Preco1 = new javax.swing.JTextField();
        Preco2 = new javax.swing.JTextField();
        BarraPreco1 = new javax.swing.JTextField();
        BarraPreco2 = new javax.swing.JTextField();
        Preco3 = new javax.swing.JTextField();
        BarraPreco3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadProdut.setEditable(false);
        txtCadProdut.setBackground(new java.awt.Color(255, 229, 77));
        txtCadProdut.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCadProdut.setText("          Cadastro de produto ");
        CdtProdut.setViewportView(txtCadProdut);

        jPanel1.add(CdtProdut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        Produto.setEditable(false);
        Produto.setBackground(new java.awt.Color(255, 255, 255));
        Produto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Produto.setText("Produto:");
        Produto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        Codigo.setEditable(false);
        Codigo.setBackground(new java.awt.Color(255, 255, 255));
        Codigo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Codigo.setText("Código:");
        Codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });
        jPanel1.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, -1));

        Marca.setEditable(false);
        Marca.setBackground(new java.awt.Color(255, 255, 255));
        Marca.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Marca.setText("Marca:");
        Marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, -1));

        BarraProduto.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 420, -1));

        BarraMarca.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 420, -1));

        BarraPreco.setBackground(new java.awt.Color(204, 204, 204));
        BarraPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(BarraPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 60, -1));

        btnSair.setBackground(new java.awt.Color(255, 229, 77));
        btnSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSair.setLabel("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 70, -1));

        btnSalvar.setBackground(new java.awt.Color(255, 229, 77));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setLabel("Salvar");
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        TabProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Produto", "Marca", "Código", "Preço", "Quantidade", "Prateleira:", "Corredor:"
            }
        ));
        Tabela.setViewportView(TabProd);

        jPanel1.add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 620, 150));

        BarraCodigo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, -1));

        btnExcluir.setBackground(new java.awt.Color(255, 229, 77));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluir.setLabel("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 229, 77));
        btnEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditar.setLabel("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 60, -1));

        btnNovo.setBackground(new java.awt.Color(255, 229, 77));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNovo.setLabel("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 60, -1));

        Preco.setEditable(false);
        Preco.setBackground(new java.awt.Color(255, 255, 255));
        Preco.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Preco.setText("Prateleira:");
        Preco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        jPanel1.add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, -1));

        Preco1.setEditable(false);
        Preco1.setBackground(new java.awt.Color(255, 255, 255));
        Preco1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Preco1.setText("Corredor:");
        Preco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Preco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco1ActionPerformed(evt);
            }
        });
        jPanel1.add(Preco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 60, -1));

        Preco2.setEditable(false);
        Preco2.setBackground(new java.awt.Color(255, 255, 255));
        Preco2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Preco2.setText("Quantidade:");
        Preco2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Preco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco2ActionPerformed(evt);
            }
        });
        jPanel1.add(Preco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, -1));

        BarraPreco1.setBackground(new java.awt.Color(204, 204, 204));
        BarraPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPreco1ActionPerformed(evt);
            }
        });
        jPanel1.add(BarraPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 110, -1));

        BarraPreco2.setBackground(new java.awt.Color(204, 204, 204));
        BarraPreco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPreco2ActionPerformed(evt);
            }
        });
        jPanel1.add(BarraPreco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 170, -1));

        Preco3.setEditable(false);
        Preco3.setBackground(new java.awt.Color(255, 255, 255));
        Preco3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Preco3.setText("Preço:");
        Preco3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Preco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco3ActionPerformed(evt);
            }
        });
        jPanel1.add(Preco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 50, -1));

        BarraPreco3.setBackground(new java.awt.Color(204, 204, 204));
        BarraPreco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPreco3ActionPerformed(evt);
            }
        });
        jPanel1.add(BarraPreco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void BarraPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPrecoActionPerformed

    private void Preco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco1ActionPerformed

    private void Preco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco2ActionPerformed

    private void BarraPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPreco1ActionPerformed

    private void BarraPreco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPreco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPreco2ActionPerformed

    private void Preco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco3ActionPerformed

    private void BarraPreco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPreco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPreco3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraCodigo;
    private javax.swing.JTextField BarraMarca;
    private javax.swing.JTextField BarraPreco;
    private javax.swing.JTextField BarraPreco1;
    private javax.swing.JTextField BarraPreco2;
    private javax.swing.JTextField BarraPreco3;
    private javax.swing.JTextField BarraProduto;
    private javax.swing.JScrollPane CdtProdut;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField Preco1;
    private javax.swing.JTextField Preco2;
    private javax.swing.JTextField Preco3;
    private javax.swing.JTextField Produto;
    private javax.swing.JTable TabProd;
    private javax.swing.JScrollPane Tabela;
    private java.awt.Button btnEditar;
    private java.awt.Button btnExcluir;
    private java.awt.Button btnNovo;
    private java.awt.Button btnSair;
    private java.awt.Button btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane txtCadProdut;
    // End of variables declaration//GEN-END:variables
}
