/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author beatr
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaLogin = new javax.swing.JPanel();
        btnAcesso1 = new java.awt.Button();
        btnCadastro = new java.awt.Button();
        Login = new javax.swing.JPanel();
        BarraUsu = new javax.swing.JTextField();
        BarraSenhaLogin = new javax.swing.JPasswordField();
        Cadeado = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Bemvindo = new javax.swing.JScrollPane();
        jTextBemvindo = new javax.swing.JTextPane();
        Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TelaLogin.setBackground(new java.awt.Color(255, 255, 255));
        TelaLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TelaLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcesso1.setActionCommand("Acessar");
        btnAcesso1.setBackground(new java.awt.Color(255, 229, 77));
        btnAcesso1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAcesso1.setLabel("Acessar");
        btnAcesso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcesso1ActionPerformed(evt);
            }
        });
        TelaLogin.add(btnAcesso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 100, 40));

        btnCadastro.setActionCommand("Acessar");
        btnCadastro.setBackground(new java.awt.Color(255, 229, 77));
        btnCadastro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCadastro.setLabel("Cadastre-se");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        TelaLogin.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 100, 40));

        Login.setBackground(new java.awt.Color(255, 229, 77));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Login.add(BarraUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 180, -1));

        BarraSenhaLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Login.add(BarraSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, -1));

        Cadeado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadeado (1).png"))); // NOI18N
        Login.add(Cadeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-usuário-24.png"))); // NOI18N
        Login.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        TelaLogin.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 280, 120));

        Bemvindo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextBemvindo.setEditable(false);
        jTextBemvindo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextBemvindo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextBemvindo.setText("Bem-vindo");
        Bemvindo.setViewportView(jTextBemvindo);

        TelaLogin.add(Bemvindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 120, -1));

        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/titulo2.png"))); // NOI18N
        TelaLogin.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinho2.jpg"))); // NOI18N
        TelaLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(TelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnAcesso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcesso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcesso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField BarraSenhaLogin;
    private javax.swing.JTextField BarraUsu;
    private javax.swing.JScrollPane Bemvindo;
    private javax.swing.JLabel Cadeado;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel TelaLogin;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Usuario;
    private java.awt.Button btnAcesso1;
    private java.awt.Button btnCadastro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextPane jTextBemvindo;
    // End of variables declaration//GEN-END:variables
}
