/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author beatr
 */
public class TelaCadUsu1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadUsu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtUsu = new javax.swing.JScrollPane();
        txtCdtUsu = new javax.swing.JTextPane();
        txtSenhaUsu = new javax.swing.JTextField();
        txtNomeUsu = new javax.swing.JTextField();
        txtEmailUsu = new javax.swing.JTextField();
        txtCPFUsu = new javax.swing.JTextField();
        txtLoginUsu = new javax.swing.JTextField();
        BarraNomeUsu = new javax.swing.JTextField();
        BarraEmailUsu = new javax.swing.JTextField();
        BarraCPFUsu = new javax.swing.JTextField();
        BarraLoginUsu = new javax.swing.JTextField();
        btnCdtUsu = new java.awt.Button();
        btnVoltarCadUsu = new java.awt.Button();
        PasswordUsu = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCdtUsu.setEditable(false);
        txtCdtUsu.setBackground(new java.awt.Color(255, 229, 77));
        txtCdtUsu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCdtUsu.setText("          Cadastro de úsuario ");
        CdtUsu.setViewportView(txtCdtUsu);

        jPanel1.add(CdtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        txtSenhaUsu.setEditable(false);
        txtSenhaUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtSenhaUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSenhaUsu.setText("Senha:");
        txtSenhaUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSenhaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenhaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 50, -1));

        txtNomeUsu.setEditable(false);
        txtNomeUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeUsu.setText("Nome:");
        txtNomeUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, -1));

        txtEmailUsu.setEditable(false);
        txtEmailUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailUsu.setText("E-mail:");
        txtEmailUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtEmailUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, -1));

        txtCPFUsu.setEditable(false);
        txtCPFUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtCPFUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCPFUsu.setText("CPF:");
        txtCPFUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCPFUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPFUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 50, -1));

        txtLoginUsu.setEditable(false);
        txtLoginUsu.setBackground(new java.awt.Color(255, 255, 255));
        txtLoginUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLoginUsu.setText("Login:");
        txtLoginUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLoginUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsuActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoginUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));

        BarraNomeUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraNomeUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 360, -1));

        BarraEmailUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraEmailUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 360, -1));

        BarraCPFUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraCPFUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, -1));

        BarraLoginUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraLoginUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, -1));

        btnCdtUsu.setActionCommand("Acessar");
        btnCdtUsu.setBackground(new java.awt.Color(255, 229, 77));
        btnCdtUsu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCdtUsu.setLabel("Cadastrar");
        btnCdtUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCdtUsuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCdtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 110, 40));

        btnVoltarCadUsu.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltarCadUsu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltarCadUsu.setLabel("Voltar");
        jPanel1.add(btnVoltarCadUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        PasswordUsu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(PasswordUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaUsuActionPerformed

    private void txtCPFUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFUsuActionPerformed

    private void txtLoginUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsuActionPerformed

    private void btnCdtUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCdtUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCdtUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadUsu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraCPFUsu;
    private javax.swing.JTextField BarraEmailUsu;
    private javax.swing.JTextField BarraLoginUsu;
    private javax.swing.JTextField BarraNomeUsu;
    private javax.swing.JScrollPane CdtUsu;
    private javax.swing.JPasswordField PasswordUsu;
    private java.awt.Button btnCdtUsu;
    private java.awt.Button btnVoltarCadUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCPFUsu;
    private javax.swing.JTextPane txtCdtUsu;
    private javax.swing.JTextField txtEmailUsu;
    private javax.swing.JTextField txtLoginUsu;
    private javax.swing.JTextField txtNomeUsu;
    private javax.swing.JTextField txtSenhaUsu;
    // End of variables declaration//GEN-END:variables
}
