/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frame;

/**
 *
 * @author beatr
 */
public class TelaTipCad extends javax.swing.JFrame {

    /** Creates new form TelaTipCad */
    public TelaTipCad() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscCdt = new javax.swing.JPanel();
        btnCli = new java.awt.Button();
        btnEmp = new java.awt.Button();
        Logo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EscCdt.setBackground(new java.awt.Color(255, 255, 255));
        EscCdt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCli.setBackground(new java.awt.Color(255, 204, 51));
        btnCli.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCli.setLabel("Cliente");
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });
        EscCdt.add(btnCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 210, 50));

        btnEmp.setBackground(new java.awt.Color(255, 204, 51));
        btnEmp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnEmp.setLabel("Empresa");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });
        EscCdt.add(btnEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 210, 50));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2020-12-26 (4).png"))); // NOI18N
        Logo2.setText("jLabel1");
        EscCdt.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-600, -120, 2070, 1090));

        getContentPane().add(EscCdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCliActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTipCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTipCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTipCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTipCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTipCad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EscCdt;
    private javax.swing.JLabel Logo2;
    private java.awt.Button btnCli;
    private java.awt.Button btnEmp;
    // End of variables declaration//GEN-END:variables

}
