/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controle.ControleProdutos;
import Model.Produtos;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beatr
 */
public class TelaCadProd extends javax.swing.JFrame {
    
    Produtos modelProdutos = new Produtos();
    ControleProdutos controleProdutos = new ControleProdutos();
    List<Produtos> listaProdutos = new ArrayList<>();
    
    
    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadProd() {
        initComponents();
        carregarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtProdut = new javax.swing.JScrollPane();
        txtCadProdut = new javax.swing.JTextPane();
        Codigo = new javax.swing.JTextField();
        Marca = new javax.swing.JTextField();
        BarraPesquisa = new javax.swing.JTextField();
        BarraMarca = new javax.swing.JTextField();
        Tabela = new javax.swing.JScrollPane();
        tblproduto = new javax.swing.JTable();
        Preco2 = new javax.swing.JTextField();
        Preco = new javax.swing.JTextField();
        btnSair2 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        BarraCodigo = new javax.swing.JTextField();
        EmpresaCadProd = new javax.swing.JTextField();
        BarraEmpPro = new javax.swing.JTextField();
        BarraPreco = new javax.swing.JTextField();
        BarraQuantidade = new javax.swing.JTextField();
        Produto1 = new javax.swing.JTextField();
        BarraProduto = new javax.swing.JTextField();
        btnVoltarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadProdut.setEditable(false);
        txtCadProdut.setBackground(new java.awt.Color(255, 229, 77));
        txtCadProdut.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCadProdut.setText("          Cadastro de produto ");
        CdtProdut.setViewportView(txtCadProdut);

        jPanel1.add(CdtProdut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        Codigo.setEditable(false);
        Codigo.setBackground(new java.awt.Color(255, 255, 255));
        Codigo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Codigo.setText("Código:");
        Codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });
        jPanel1.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, -1));

        Marca.setEditable(false);
        Marca.setBackground(new java.awt.Color(255, 255, 255));
        Marca.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Marca.setText("Marca:");
        Marca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, -1));

        BarraPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 200, -1));

        BarraMarca.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 420, -1));

        tblproduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblproduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Empresa", "Produto", "Marca", "Preço", "Quantidade"
            }
        ));
        Tabela.setViewportView(tblproduto);

        jPanel1.add(Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 620, 150));

        Preco2.setEditable(false);
        Preco2.setBackground(new java.awt.Color(255, 255, 255));
        Preco2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Preco2.setText("Quantidade:");
        Preco2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Preco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco2ActionPerformed(evt);
            }
        });
        jPanel1.add(Preco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, -1));

        Preco.setEditable(false);
        Preco.setBackground(new java.awt.Color(255, 255, 255));
        Preco.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Preco.setText("Preço:");
        Preco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        jPanel1.add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 50, -1));

        btnSair2.setBackground(new java.awt.Color(255, 229, 77));
        btnSair2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair2.setText("Sair");
        btnSair2.setToolTipText("");
        btnSair2.setActionCommand("");
        btnSair2.setBorderPainted(false);
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 70, -1));

        btnEditar.setBackground(new java.awt.Color(255, 229, 77));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditar.setText("Atualizar");
        btnEditar.setToolTipText("");
        btnEditar.setActionCommand("");
        btnEditar.setBorderPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, -1));

        btnExcluir.setBackground(new java.awt.Color(255, 229, 77));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setActionCommand("");
        btnExcluir.setBorderPainted(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 70, -1));

        btnSalvar.setBackground(new java.awt.Color(255, 229, 77));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.setActionCommand("");
        btnSalvar.setBorderPainted(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, -1));

        BarraCodigo.setEditable(false);
        BarraCodigo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, -1));

        EmpresaCadProd.setEditable(false);
        EmpresaCadProd.setBackground(new java.awt.Color(255, 255, 255));
        EmpresaCadProd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        EmpresaCadProd.setText("Empresa:");
        EmpresaCadProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(EmpresaCadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, -1));

        BarraEmpPro.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraEmpPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 420, -1));

        BarraPreco.setBackground(new java.awt.Color(204, 204, 204));
        BarraPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(BarraPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 170, -1));

        BarraQuantidade.setBackground(new java.awt.Color(204, 204, 204));
        BarraQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraQuantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(BarraQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 60, -1));

        Produto1.setEditable(false);
        Produto1.setBackground(new java.awt.Color(255, 255, 255));
        Produto1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Produto1.setText("Produto:");
        Produto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(Produto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        BarraProduto.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 420, -1));

        btnVoltarProd.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltarProd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltarProd.setText("Voltar");
        btnVoltarProd.setToolTipText("");
        btnVoltarProd.setActionCommand("");
        btnVoltarProd.setBorderPainted(false);
        btnVoltarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void Preco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco2ActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        // TODO add your handling code here:
        TelaLogin objeto8 = new TelaLogin();
        objeto8.setVisible(true);
    }//GEN-LAST:event_btnSair2ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        modelProdutos = new Produtos();
        modelProdutos.setProEmpresa(BarraEmpPro.getText());
        modelProdutos.setProDescricao(BarraProduto.getText());
        modelProdutos.setProMarca(BarraMarca.getText());
        modelProdutos.setProPreco(Double.parseDouble(BarraPreco.getText()));
        modelProdutos.setProQuat(Integer.valueOf(BarraQuantidade.getText()));
        if(controleProdutos.salvarProdutosControle(modelProdutos)){
            JOptionPane.showMessageDialog(this, "Cadastro realizado", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            limparFormularioProduto();
            carregarProdutos();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed
    
     /**
     * Limpar formúlario de cadastro de produtos
     * @param void 
     */
    private void limparFormularioProduto(){
        BarraEmpPro.setText("");
        BarraProduto.setText("");
        BarraMarca.setText("");
        BarraPreco.setText("");
        BarraQuantidade.setText("");
    }
    
    private void carregarProdutos(){
        listaProdutos = controleProdutos.getListaProdutosControle();
        DefaultTableModel modelo4 = (DefaultTableModel) tblproduto.getModel();
        modelo4.setNumRows(0);
        
        for (int i = 0; i < listaProdutos.size(); i++){
            modelo4.addRow(new Object[]{
                listaProdutos.get(i).getProId(),
                listaProdutos.get(i).getProEmpresa(),
                listaProdutos.get(i).getProDescricao(),
                listaProdutos.get(i).getProMarca(),
                listaProdutos.get(i).getProPreco(),
                listaProdutos.get(i).getProQuat()
            });
        }
    }   
    
    
    private void BarraPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraPrecoActionPerformed

    private void BarraQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraQuantidadeActionPerformed

    private void btnVoltarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarProdActionPerformed
        // TODO add your handling code here:
        TelaTipCad objeto9 = new TelaTipCad();
        objeto9.setVisible(true);
    }//GEN-LAST:event_btnVoltarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraCodigo;
    private javax.swing.JTextField BarraEmpPro;
    private javax.swing.JTextField BarraMarca;
    private javax.swing.JTextField BarraPesquisa;
    private javax.swing.JTextField BarraPreco;
    private javax.swing.JTextField BarraProduto;
    private javax.swing.JTextField BarraQuantidade;
    private javax.swing.JScrollPane CdtProdut;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField EmpresaCadProd;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField Preco2;
    private javax.swing.JTextField Produto1;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarProd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblproduto;
    private javax.swing.JTextPane txtCadProdut;
    // End of variables declaration//GEN-END:variables
}
