/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controle.ControleEmpresa;
import Model.Empresa;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author beatr
 */
public class TelaCadEmp extends javax.swing.JFrame {

    Empresa modelEmpresa = new Empresa();
    ControleEmpresa controleEmpresa = new ControleEmpresa();
    List<Empresa> listaEmpresa = new ArrayList<>();
    
    
    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadEmp() {
        initComponents();
        carregarEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CdtEmp = new javax.swing.JScrollPane();
        txtCadEmp = new javax.swing.JTextPane();
        txtEmailEmp = new javax.swing.JTextField();
        txtFoneEmp = new javax.swing.JTextField();
        BarraCidade = new javax.swing.JTextField();
        BarraEmailEmp = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        txtDadoEmp = new javax.swing.JTextField();
        txtNomeEmp = new javax.swing.JTextField();
        BarraNomeEmp = new javax.swing.JTextField();
        txtCidadeEmp = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        BarraBairro = new javax.swing.JTextField();
        UF = new javax.swing.JTextField();
        BarraUF = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        BarraEndereco = new javax.swing.JTextField();
        btnVoltarTip = new javax.swing.JButton();
        txtNumeroEmp = new javax.swing.JTextField();
        BarraFoneEmp = new javax.swing.JFormattedTextField();
        BarraCnpj = new javax.swing.JFormattedTextField();
        BarraNumero = new javax.swing.JTextField();
        btnFinalizar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpresas = new javax.swing.JTable();
        btnAtuaCadEmp = new javax.swing.JButton();
        btnExcluirCadEmp = new javax.swing.JButton();
        BarraPesqEmp = new javax.swing.JTextField();
        btnPesqCadEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadEmp.setEditable(false);
        txtCadEmp.setBackground(new java.awt.Color(255, 229, 77));
        txtCadEmp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtCadEmp.setText("          Cadastro de Empresa ");
        CdtEmp.setViewportView(txtCadEmp);

        jPanel1.add(CdtEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 330, 40));

        txtEmailEmp.setEditable(false);
        txtEmailEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailEmp.setText("E-mail:");
        txtEmailEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 50, -1));

        txtFoneEmp.setEditable(false);
        txtFoneEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtFoneEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFoneEmp.setText("Telefone:");
        txtFoneEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtFoneEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoneEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtFoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, -1));

        BarraCidade.setBackground(new java.awt.Color(204, 204, 204));
        BarraCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, -1));

        BarraEmailEmp.setBackground(new java.awt.Color(204, 204, 204));
        BarraEmailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraEmailEmpActionPerformed(evt);
            }
        });
        jPanel1.add(BarraEmailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 360, -1));

        txtCNPJ.setEditable(false);
        txtCNPJ.setBackground(new java.awt.Color(255, 255, 255));
        txtCNPJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCNPJ.setText("CNPJ:");
        txtCNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJActionPerformed(evt);
            }
        });
        jPanel1.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, -1));

        txtDadoEmp.setEditable(false);
        txtDadoEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtDadoEmp.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        txtDadoEmp.setText("Dados da Empresa");
        txtDadoEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtDadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        txtNomeEmp.setEditable(false);
        txtNomeEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeEmp.setText("Nome:");
        txtNomeEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 50, -1));

        BarraNomeEmp.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraNomeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 360, -1));

        txtCidadeEmp.setEditable(false);
        txtCidadeEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtCidadeEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCidadeEmp.setText("Cidade:");
        txtCidadeEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtCidadeEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 50, -1));

        txtBairro.setEditable(false);
        txtBairro.setBackground(new java.awt.Color(255, 255, 255));
        txtBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBairro.setText("Bairro:");
        txtBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 50, -1));

        BarraBairro.setBackground(new java.awt.Color(204, 204, 204));
        BarraBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraBairroActionPerformed(evt);
            }
        });
        jPanel1.add(BarraBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, -1));

        UF.setEditable(false);
        UF.setBackground(new java.awt.Color(255, 255, 255));
        UF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UF.setText("UF:");
        UF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFActionPerformed(evt);
            }
        });
        jPanel1.add(UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 30, -1));

        BarraUF.setBackground(new java.awt.Color(204, 204, 204));
        BarraUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraUFActionPerformed(evt);
            }
        });
        jPanel1.add(BarraUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 60, -1));

        txtEndereco.setEditable(false);
        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEndereco.setText("Endereço:");
        txtEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, -1));

        BarraEndereco.setBackground(new java.awt.Color(204, 204, 204));
        BarraEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(BarraEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 360, -1));

        btnVoltarTip.setBackground(new java.awt.Color(255, 229, 77));
        btnVoltarTip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltarTip.setText("Voltar");
        btnVoltarTip.setToolTipText("");
        btnVoltarTip.setActionCommand("");
        btnVoltarTip.setBorderPainted(false);
        btnVoltarTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTipActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        txtNumeroEmp.setEditable(false);
        txtNumeroEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroEmp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNumeroEmp.setText("Nº:");
        txtNumeroEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNumeroEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEmpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 30, -1));

        BarraFoneEmp.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraFoneEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(BarraFoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 240, -1));

        BarraCnpj.setBackground(new java.awt.Color(204, 204, 204));
        try {
            BarraCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##. ###. ###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        BarraCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraCnpjActionPerformed(evt);
            }
        });
        jPanel1.add(BarraCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 250, -1));

        BarraNumero.setBackground(new java.awt.Color(204, 204, 204));
        BarraNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(BarraNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 60, -1));

        btnFinalizar1.setBackground(new java.awt.Color(255, 229, 77));
        btnFinalizar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFinalizar1.setText("Salvar");
        btnFinalizar1.setToolTipText("");
        btnFinalizar1.setActionCommand("");
        btnFinalizar1.setBorderPainted(false);
        btnFinalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, 20));

        tblEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Email", "Telefone", "CNPJ", "Endereço", "Bairro", "Cidade", "Nº", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblEmpresas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 660, 160));

        btnAtuaCadEmp.setBackground(new java.awt.Color(255, 229, 77));
        btnAtuaCadEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtuaCadEmp.setText("Atualizar");
        btnAtuaCadEmp.setToolTipText("");
        btnAtuaCadEmp.setActionCommand("");
        btnAtuaCadEmp.setBorderPainted(false);
        btnAtuaCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtuaCadEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtuaCadEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 90, 20));

        btnExcluirCadEmp.setBackground(new java.awt.Color(255, 229, 77));
        btnExcluirCadEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirCadEmp.setText("Excluir");
        btnExcluirCadEmp.setToolTipText("");
        btnExcluirCadEmp.setActionCommand("");
        btnExcluirCadEmp.setBorderPainted(false);
        btnExcluirCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCadEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirCadEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, 20));

        BarraPesqEmp.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(BarraPesqEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 250, -1));

        btnPesqCadEmp.setBackground(new java.awt.Color(255, 229, 77));
        btnPesqCadEmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesqCadEmp.setText("Pesquisar");
        btnPesqCadEmp.setToolTipText("");
        btnPesqCadEmp.setActionCommand("");
        btnPesqCadEmp.setBorderPainted(false);
        btnPesqCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCadEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesqCadEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFoneEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoneEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoneEmpActionPerformed

    private void txtEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEmpActionPerformed

    private void txtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJActionPerformed

    private void BarraCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCidadeActionPerformed

    private void BarraBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraBairroActionPerformed

    private void UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFActionPerformed

    private void BarraUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraUFActionPerformed

    private void BarraEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraEnderecoActionPerformed
    
    private void btnVoltarTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTipActionPerformed
        // TODO add your handling code here:
        TelaTipCad objeto5 = new TelaTipCad();
        objeto5.setVisible(true);
    }//GEN-LAST:event_btnVoltarTipActionPerformed

    private void txtNumeroEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEmpActionPerformed

    private void BarraEmailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraEmailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraEmailEmpActionPerformed

    private void BarraCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraCnpjActionPerformed

    private void BarraNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraNumeroActionPerformed

    private void btnFinalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar1ActionPerformed
        // TODO add your handling code here:
        modelEmpresa = new Empresa();
        modelEmpresa.setEmpNome(BarraNomeEmp.getText());
        modelEmpresa.setEmpEmail(BarraEmailEmp.getText());
        modelEmpresa.setEmpFone(BarraFoneEmp.getText());
        modelEmpresa.setEmpCNPJ(BarraCnpj.getText());
        modelEmpresa.setEmpEnd(BarraEndereco.getText());
        modelEmpresa.setEmpBairro(BarraBairro.getText());
        modelEmpresa.setEmpCidade(BarraCidade.getText());
        modelEmpresa.setEmpNumero(BarraNumero.getText());
        modelEmpresa.setEmpEstado(BarraUF.getText());
        //controleEmpresa.salvarEmpresaControle(modelEmpresa);
        formularioEmpVazio();
    }//GEN-LAST:event_btnFinalizar1ActionPerformed

    private void btnAtuaCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuaCadEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtuaCadEmpActionPerformed

    private void btnExcluirCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCadEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirCadEmpActionPerformed

    private void btnPesqCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCadEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesqCadEmpActionPerformed

    private void formularioEmpVazio(){
        if((BarraNomeEmp.getText().length() > 0)
                && (BarraEmailEmp.getText().length() > 0)
                && (BarraFoneEmp.getText().length() > 0)
                && (BarraCnpj.getText().length() > 0)
                && (BarraEndereco.getText().length() > 0)
                && (BarraBairro.getText().length() > 0)
                && (BarraCidade.getText().length() > 0)
                && (BarraNumero.getText().length() > 0)
                && (BarraUF.getText().length() > 0)){
            JOptionPane.showMessageDialog(this, "Cadastro realizado!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            controleEmpresa.salvarEmpresaControle(modelEmpresa);
            limparFormularioEmp();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "Erro", JOptionPane.ERROR_MESSAGE);            
        }
            
    }
    /**
     * Limpar formúlario de cadastro de empresa
     * @param void 
     */
    private void limparFormularioEmp(){
        BarraNomeEmp.setText("");
        BarraEmailEmp.setText("");
        BarraFoneEmp.setText("");
        BarraCnpj.setText("");
        BarraEndereco.setText("");
        BarraBairro.setText("");
        BarraCidade.setText("");
        BarraNumero.setText("");
        BarraUF.setText("");        
    }
    
    private void carregarEmpresa(){
        listaEmpresa = controleEmpresa.getListaEmpresaControle();
        DefaultTableModel modelo3 = (DefaultTableModel) tblEmpresas.getModel();
        modelo3.setNumRows(0);
        
        for (int i = 0; i < listaEmpresa.size(); i++){
            modelo3.addRow(new Object[]{
                listaEmpresa.get(i).getEmpId(),
                listaEmpresa.get(i).getEmpNome(),
                listaEmpresa.get(i).getEmpEmail(),
                listaEmpresa.get(i).getEmpFone(),
                listaEmpresa.get(i).getEmpCNPJ(),
                listaEmpresa.get(i).getEmpEnd(),
                listaEmpresa.get(i).getEmpBairro(),
                listaEmpresa.get(i).getEmpCidade(),
                listaEmpresa.get(i).getEmpNumero(),
                listaEmpresa.get(i).getEmpEstado()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBairro;
    private javax.swing.JTextField BarraCidade;
    private javax.swing.JFormattedTextField BarraCnpj;
    private javax.swing.JTextField BarraEmailEmp;
    private javax.swing.JTextField BarraEndereco;
    private javax.swing.JFormattedTextField BarraFoneEmp;
    private javax.swing.JTextField BarraNomeEmp;
    private javax.swing.JTextField BarraNumero;
    private javax.swing.JTextField BarraPesqEmp;
    private javax.swing.JTextField BarraUF;
    private javax.swing.JScrollPane CdtEmp;
    private javax.swing.JTextField UF;
    private javax.swing.JButton btnAtuaCadEmp;
    private javax.swing.JButton btnExcluirCadEmp;
    private javax.swing.JButton btnFinalizar1;
    private javax.swing.JButton btnPesqCadEmp;
    private javax.swing.JButton btnVoltarTip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpresas;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextPane txtCadEmp;
    private javax.swing.JTextField txtCidadeEmp;
    private javax.swing.JTextField txtDadoEmp;
    private javax.swing.JTextField txtEmailEmp;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFoneEmp;
    private javax.swing.JTextField txtNomeEmp;
    private javax.swing.JTextField txtNumeroEmp;
    // End of variables declaration//GEN-END:variables
}
